spring:
  application:
    name: FinanceTracker
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: postgres
    password: harsh
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  jwt:
    secret: dasfasdfadsfas
    access-token-expiration: 7200 #5minutes
    refresh-token-expiration: 604800 #7d
  threads:
    virtual:
      enabled: true
